### ISSUE TITLE
Cannot generate ./ChatGPT

### ISSUE THREAD

**Issue by sucv** [deni2312/ChatGPT-Cpp#1]
There are bugs in the instruction below.

```
cd ChatGPT-Cpp
mkdir build
cd build
cmake -B build/ -S . -DCMAKE_TOOLCHAIN_FILE=vcpkgdirectory/scripts/buildsystems/vcpkg.cmake
cd build
cmake --build .
./ChatGPT
```

First, the first `cd build` should not exist, because the newly made `build/` contains nothing.
Second, `cmake --build .` raises error saying 

```
/usr/bin/ld: cannot open output file ChatGPT: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ChatGPT.dir/build.make:90: ChatGPT] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/ChatGPT.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

Seems that `ChatGPT` already existed as a directory, so that the executable cannot be generated in the same name.

**Comment by deni2312** [comment]
Fixed both problems, thanks for the issue.

**Comment by sucv** [comment]
Thanks for the prompt response!
