### ISSUE TITLE
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::parse_error'

### ISSUE THREAD

**Issue by SummrWhit** [deni2312/ChatGPT-Cpp#2]
Hello, I'm trying this project to experience ChatGPT, but when I run the object compiled, I had a crash, the error log is:
./Chat_GPT [my api_key]
1. Serenity
2. Enthusiasm
3. Perseverance
4. Affection
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
已放弃 (核心已转储)
pls help me,tks.

**Comment by deni2312** [comment]
If you're running the main example, are you sure that the sound.mp3 file in the same directory as the executable?

**Comment by SummrWhit** [comment]
yes, it has a sound.mp3 file in build directory
and it still crash

**Comment by SummrWhit** [comment]
I compile it on ubuntu20.04, and I'm not sure whether it can affect sth...

**Comment by deni2312** [comment]
That's look weird, have you tried to remove the whisper part?

**Comment by SummrWhit** [comment]
yes, I have tried, but it still crash...
